// Code generated by "stringer -type=EventType -output=event_string.go"; DO NOT EDIT.

package scheduler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APUFrameSequencer-0]
	_ = x[APUFrameSequencer2-1]
	_ = x[APUChannel1-2]
	_ = x[APUChannel2-3]
	_ = x[APUChannel3-4]
	_ = x[APUSample-5]
	_ = x[EIPending-6]
	_ = x[EIHaltDelay-7]
	_ = x[PPUHandleVisualLine-8]
	_ = x[PPUHandleGlitchedLine0-9]
	_ = x[PPULockVRAMRead-10]
	_ = x[PPUUnlockVRAMRead-11]
	_ = x[PPULockOAMRead-12]
	_ = x[PPUUnlockOAMRead-13]
	_ = x[PPULockOAMWrite-14]
	_ = x[PPUUnlockOAMWrite-15]
	_ = x[PPUHandleOffscreenLine-16]
	_ = x[DMAStartTransfer-17]
	_ = x[DMAEndTransfer-18]
	_ = x[DMATransfer-19]
	_ = x[TimerTIMAReload-20]
	_ = x[TimerTIMAFinishReload-21]
	_ = x[TimerTIMAIncrement-22]
	_ = x[SerialBitTransfer-23]
	_ = x[SerialBitInterrupt-24]
	_ = x[CameraShoot-25]
	_ = x[SerialExternalClock-26]
}

const _EventType_name = "APUFrameSequencerAPUFrameSequencer2APUChannel1APUChannel2APUChannel3APUSampleEIPendingEIHaltDelayPPUHandleVisualLinePPUHandleGlitchedLine0PPULockVRAMReadPPUUnlockVRAMReadPPULockOAMReadPPUUnlockOAMReadPPULockOAMWritePPUUnlockOAMWritePPUHandleOffscreenLineDMAStartTransferDMAEndTransferDMATransferTimerTIMAReloadTimerTIMAFinishReloadTimerTIMAIncrementSerialBitTransferSerialBitInterruptCameraShootSerialExternalClock"

var _EventType_index = [...]uint16{0, 17, 35, 46, 57, 68, 77, 86, 97, 116, 138, 153, 170, 184, 200, 215, 232, 254, 270, 284, 295, 310, 331, 349, 366, 384, 395, 414}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
