name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.27'
      - name: install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc libgl1-mesa-dev libegl-dev xorg-dev libsdl2-dev libwayland-dev wayland-protocols libxkbcommon-dev
      - name: build
        run: go build -trimpath -ldflags="-s -w" -o gomeboy-linux-amd64 .
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: gomeboy-linux-amd64
