name: gomeboy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_regressions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: setup go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27'
      - name: install dependencies
        run: go mod download
      - name: tests
        run: go test -tags test -v ./tests -run Test_Regressions
